import type { Metadata } from "next";
import { Cantarell } from "next/font/google";
import "../styles/globals.css";

const font = Cantarell({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Andy Sorge - Developer Portfolio</title>
      <link rel="icon" href="/favicon.ico" />
    </head>
      <body className={font.className}>{children}</body>
    </html>
  );
}
